title: thephotonbooth.com
description: Amateur astrophotography by Matt Booth
author: Matt Booth
url: "https://thephotonbooth.com"
baseurl: "/matt-booth"

permalink: /:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - AGENTS.md
  - vendor
